### ISSUE TITLE
Unable to display Suspicious Stew status effects

### ISSUE THREAD

**Issue by Suel-ki** [DaFuqs/FoodEffectTooltips#4]
![i1](https://user-images.githubusercontent.com/116934864/209736233-9ce3a67e-78d1-4585-a379-f75947dbc86d.png)
![i2](https://user-images.githubusercontent.com/116934864/209736398-2a906980-b69b-433a-9b8e-9107877b4b15.png)

**Comment by DaFuqs** [comment]
Well, the main clue with Suspicious Stew is that you don't see what effect it has. But I can definitely add a config toggle for that, sure.

Also I saw your Forge port yesterday, thank you! I will happily add a link on the fabric versions pages to link to your port for all the Forge people out there on Curseforge, and Modrinth.

**Comment by Suel-ki** [comment]
Well, I wasn't thoughtful, but I think it's a good idea. 

Another issue is that food effect tooltips are displayed below the advanced tooltip.

If you would like to add a link that would be great, thanks.

**Comment by DaFuqs** [comment]
Done in v1.1.1
