### ISSUE TITLE
1.20.3/4 Support

### ISSUE THREAD

**Issue by R00tB33rMan** [DaFuqs/FoodEffectTooltips#6]
It's me again! Just wanted to notify 1.20.3/4's release. Seemed to help you last time so I thought I should push out another notice. Really appreciate your dedication towards this project!

**Comment by DaFuqs** [comment]
Will release shortly ✅

**Comment by DaFuqs** [comment]
1.20.4 done!

**Comment by R00tB33rMan** [comment]
Appreciate it a ton! Excellent work!
