### ISSUE TITLE
Slight compat improvement with FD

### ISSUE THREAD

**Issue by anoomolu** [DaFuqs/FoodEffectTooltips#7]
Hiya, thanks for making such a useful mod!! I prefer this one over the built-in Farmer’s Delight tooltips as it just looks cleaner + works for vanilla foods.

One thing I noticed is that the effects conferred by horse feed and dog food aren’t in the tooltip with this mod - I was wondering if it’d be possible to add compat for this? 

edit: after another pass, seems like Hot Cocoa, Milk Bottles and Melon Juice don't have their effects listed either (found [here](https://github.com/vectorwing/FarmersDelight/wiki/Drinks)). Might be an opportunity to add a tooltip to Milk Buckets too?

Using Food Effect Tooltips and Farmer’s Delight Refabricated for 1.20.1.

**Comment by DaFuqs** [comment]
I will look into it, thank you!

**Comment by DaFuqs** [comment]
The link you referenced is for the Forge version fo the mod. You are probably running this one?
Modrinth: https://modrinth.com/mod/farmers-delight-refabricated
Source Code: https://github.com/MehVahdJukaar/FarmersDelight

The values for those foods seem to be added in a [custom way via event](https://github.com/MehVahdJukaar/FarmersDelight/blob/901c415a7bcec5e5102fc35c46176c4317b5ecb5/src/main/java/vectorwing/farmersdelight/common/item/DogFoodItem.java#L52), so FoodEffectTooltips can not find them. There also does not seem to be an API of sorts to grab the effects, for example doog food has.

@MerchantPug Got a good idea how other mods could grab the food / status effect values from Dog food and the other items mentioned above?

**Comment by ChrysanthCow** [comment]
> The link you referenced is for the Forge version fo the mod. You are probably running this one?
> Modrinth: https://modrinth.com/mod/farmers-delight-refabricated
> Source Code: https://github.com/MehVahdJukaar/FarmersDelight
> 
> The values for those foods seem to be added in a [custom way via event](https://github.com/MehVahdJukaar/FarmersDelight/blob/901c415a7bcec5e5102fc35c46176c4317b5ecb5/src/main/java/vectorwing/farmersdelight/common/item/DogFoodItem.java#L52), so FoodEffectTooltips can not find them. There also does not seem to be an API of sorts to grab the effects, for example doog food has.
> 
> @MerchantPug Got a good idea how other mods could grab the food / status effect values from Dog food and the other items mentioned above?

Hi, I'm honestly a little unsure. I'd have to look into hooks for all of these.

Thanks for the ping.
