### ISSUE TITLE
Mod seems to work on 1.21

### ISSUE THREAD

**Issue by anoomolu** [DaFuqs/FoodEffectTooltips#8]
Hiya!

Was curious whether the 1.20.6 release would work on 1.21 because the versions don't seem thaat different (although of course internals have changed a lot during recent updates), and found that Food Effect Tooltips works fine:

![image](https://github.com/DaFuqs/FoodEffectTooltips/assets/77850233/6e8bf12e-c8c3-4e2c-80c9-e2618031c335)

**Comment by DaFuqs** [comment]
Looks like I totally forgot putting the updated version on modrinth. Will get to it right away. ✅
