### ISSUE TITLE
Crashes while used with EMI

### ISSUE THREAD

**Issue by NolanHewitt** [DaFuqs/FoodEffectTooltips#9]
Seems to crash while using EMI when opening the creative menu. In survival EMI fails to load. Could this be fixed?
[crash-2024-10-19_21.36.11-client.txt](https://github.com/user-attachments/files/17448201/crash-2024-10-19_21.36.11-client.txt)

**Comment by DaFuqs** [comment]
One of the items in your pack wants to give a status effect when eaten, but that status effect does not exist.
Hence when EMI tries to load the tooltip of that item and FoodEffectTooltip wants to look up the language key for that effect, it crashes.

This definitely looks like an oversight/error of one of the other mods in your pack. Can you find out which it is by removing mods, please?

**Comment by NolanHewitt** [comment]
Looks like it was the mod Create: Garnished. They just updated and the changelog says it fixed an issue related to this mod. After updating that mod there are no crashes anymore.
